### ISSUE TITLE
Provide Clone for multiplex::Client

### ISSUE THREAD

**Issue by theli-ua** [tower-rs/tokio-tower#13]
While it doesn't make any sense for pipelined, for multiplexed client a use case for using same transport from multiple places to have multiple outstanding requests is viable.

**Comment by jonhoo** [comment]
Ah, yes, so, to do that you'd just wrap the client using `tower-buffer`!

**Comment by theli-ua** [comment]
Yeah, that works, thanks Jon. 
With that I guess it won't make much sense for an effort to make mediator and friends thread safe.

**Comment by jonhoo** [comment]
Right, that was exactly my thinking — the multiplexing should be done by a service that is explicitly written for that purpose :)

**Comment by theli-ua** [comment]
@jonhoo Having another thought of that - this isn't really solved by Buffer. Buffer will still , well, buffer requests and will only allow at most 1 request `on the wire`, isn't it? Since buffer will have exactly one background worker that just pulls one request from a channel at a time, awaits on response from server to that request and so forth. Or am I mistaken? So there is no multiplexing at all, everything is converted to a pipeline. While technically since response is matched to request by a tag it should be possible to have multiple requests send out and the responses received in arbitrary order.

**Comment by jonhoo** [comment]
Oh, no, multiplex will allow many requests to be in flight at the same time. When it receives a request, it sends that request to the remote end, but it does not _also_ wait for the response. Instead, it goes on to receive more requests (and sends those too). Only when no more requests are available does it read responses.

**Comment by theli-ua** [comment]
Right, but with Buffer in front of it as you suggest above that doesn't happen since buffer will send 1 request and then will await for response before sending another one, isn't it?

**Comment by jonhoo** [comment]
No, buffer will not wait for any given request to be resolved. All buffer does is send back the response _future_ that the inner service (which would be tokio tower) returns. It never waits for that future, and does not block you from sending more requests without waiting for it.

**Comment by theli-ua** [comment]
Ah, that makes total sense. I misread buffer impl then. Thanks again.
