### ISSUE TITLE
Does receiving a multiplexed response with a bad response identifier cause a panic?

### ISSUE THREAD

**Issue by saleemrashid** [tower-rs/tokio-tower#15]
Reading the multiplexed client implementation, it looks like a response with an unknown response identifier will cause a panic, due to the use of `expect`.

https://github.com/tower-rs/tokio-tower/blob/fe6fd0c273759ece4e2e9db559f0507b1fcb02e1/src/multiplex/client.rs#L323-L327

**Comment by jonhoo** [comment]
Yes, that is correct, as this is indicative of a much more serious protocol misalignment problem. Do you feel like it should be handled differently?

**Comment by saleemrashid** [comment]
I don't think that a misbehaving server should ever be able to crash the client application. While that _might_ make sense in an application built completely around one client (although, even then, the author might want to handle this failure gracefully), it definitely doesn't make sense if a client is being used as a small component of a bigger application. Imagine if, every time you use an HTTP client to connect to a untrusted server, that HTTP server could crash your application?

It's difficult to say how it should be handled differently - I'm not great at API design, and I'm also not using this library directly because the protocol I have to implement has too many edge cases that don't fall neatly into 1:1 request:response.

**Comment by jonhoo** [comment]
Hmm, yeah, that's a good point. @LucioFranco what do you think? We could have the client error here, though it's not entirely clear how we communicate that error neatly to the caller. Specifically, the error is detected in the spawned connection worker, and the very nature of the error means that it's not related to a particular request. I suppose we could do something like `tower-buffer` and have the worker save the error in an `Arc` somewhere, issue an error to all current clients, shut down the connection (preventing future requests), and then provide some call on clients that lets them access the error after the fact?

**Comment by LucioFranco** [comment]
I think instead of an expect and error message seems fine here. We don't need to communicate it back code wise but should be able to just log an error. I think that is what things like h2 do? I haven't checked but it seems like that is what they'd do.

**Comment by saleemrashid** [comment]
I wonder if you can let the caller decide the "strategy", i.e. whether unmatched responses are dropped or are hard errors. The other question is how the caller can choose to handle responses with no request identifier at all (e.g. some servers send unsolicited "heartbeat" messages) - I'm working on my first ever Tokio project (and second ever Rust project for years), so I'm incredibly new to this but I presume this is handled by implementing some kind of middleware that handles and drops those responses before they reach this layer of the stack?

**Comment by jonhoo** [comment]
Just logging an error seems odd too though. We already have a mechanism for the caller to define what happens on error ([`Client::with_error_handler`](https://github.com/tower-rs/tokio-tower/blob/fe6fd0c273759ece4e2e9db559f0507b1fcb02e1/src/multiplex/client.rs#L179)), so maybe that's sufficient?

@saleemrashid I think having support for unsolicited messages is slightly different. In my mind at least, that should happen at a different layer than `tokio-tower`. Specifically, I think it is probably reasonable for the `Sink + Stream` implementation to filter out any such non-service messages before they impact `tokio-tower`.

**Comment by saleemrashid** [comment]
As a reference, here's an example of `h2` handling an unknown stream identifier: https://github.com/hyperium/h2/blob/cfc7584eb6616768e88271bb3e0b055154fcd00c/src/proto/streams/streams.rs#L270-L287

**Comment by saleemrashid** [comment]
> @saleemrashid I think having support for unsolicited messages is slightly different. In my mind at least, that should happen at a different layer than `tokio-tower`. Specifically, I think it is probably reasonable for the `Sink + Stream` implementation to filter out any such non-service messages before they impact `tokio-tower`.

Agreed, just wanted to confirm that I'm understanding how Tokio/Tower is supposed to work :smile:

**Comment by LucioFranco** [comment]
returning a connection error though would invalidate inflight requests which may cause issues on the server side?

**Comment by jonhoo** [comment]
> As a reference, here's an example of `h2` handling an unknown stream identifier:

Ah, interesting. I think a log message is certainly warranted, and then returning an error to the registered error handler seems like the next best thing to do. The question, I think, is whether the worker should continue or exit. With the proposed "pass it to the error handler" approach, the user only really has the options of "ignore" and "panic", not "fail this connection".

> Agreed, just wanted to confirm that I'm understanding how Tokio/Tower is supposed to work

Hehe, how tokio/tower is "supposed" to work is still very much in flux, so input welcome. This crate is basically a starting point for "maybe this way" (hence the 0.3 version), but things will likely change more. My instinct says that non-request/responses should be handled in a different "layer" though.

> returning a connection error though would invalidate inflight requests which may cause issues on the server side?

Yeah, having the worker exit would basically tear down that entire connection. Though I could also see an argument for that being the right thing to do. Getting a bad request identifier in a reply indicates that the client and server have gotten out of sync somehow, or that the server is bad, both of which seem sufficiently severe that we should shut down.

Maybe the solution to both above problems is this: if a mismatch is detected, the worker passes an error to the error handler, and then exits. Now, the user has a choice of "just tear down the connection" and "panic", and no "ignore" choice. That _seems_ like the right trade-off for me?

**Comment by saleemrashid** [comment]
> Getting a bad request identifier in a reply indicates that the client and server have gotten out of sync somehow, or that the server is bad, both of which seem sufficiently severe that we should shut down.

It depends on the kind of protocol you're implementing. In HTTP/2.0, I assume that's the right decision - it's a very well-specified protocol. If you're implementing something more ad-hoc, especially if you don't control the server, you might want to handle this more gracefully?

**Comment by jonhoo** [comment]
I guess as a user I would still expect that to shut down the connection (though I agree, it might not always make sense to panic). Letting it "limp along" after a mismatch like that sounds like it would be a recipe for further issues down the line. For example, this might indicate that the server has gotten connections mixed up, and suddenly you might see a response that _happens_ to line up, but is _actually_ for a different request, at which point you can get really bad application logic issues that may even be destructive. That's the sort of stuff I want to guard against.

**Comment by saleemrashid** [comment]
> For example, this might indicate that the server has gotten connections mixed up, and suddenly you might see a response that _happens_ to line up, but is _actually_ for a different request

It does very much depend on the kind of protocol you're implementing. I happen to be implementing one where the response is not directly tied to the request - i.e. a `ping` is expected to cause a `pong` at _some point in the near future_ but you don't treat the `pong` as a "response" (I hate this protocol very much, but it is what it is, c'est la vie).

This isn't directly applicable to what you're saying, but is an example that some protocols are just _bad_. As long as silently dropping unmatched packets isn't the default behaviour, I think it should be up to the user. Maybe with some scary API names and scary documentation warnings.

**Comment by jonhoo** [comment]
Ah, sorry, yes, in a protocol like that, you wouldn't use `tokio_tower::Multiplex`. If it's just a thing that has requests and a thing that has responses, just use `Sink` and `Stream` directly. `Multiplex` is specifically for when you have tagged requests and responses that are linked :)

**Comment by jonhoo** [comment]
Unfortunately I think this would be a breaking change, since it requires adding a variant to `Error`. A similar thing can also happen for `Pipelined`, if you get a response but don't have a pending request. Both of those should probably map to an error like `Error::Desynchronized`. I'll leave this open as a reminder for the next breaking release! I don't _think_ it's urgent enough to do a breaking release right now.

**Comment by jonhoo** [comment]
This fix is now live in 0.4 :tada:
